#!/usr/bin/env python3
"""
OmniRecon AI — Smart Backend Launcher
======================================
Guides you through API key setup, installs packages, and starts the server.

Usage:
    python start_backend.py
"""

import os
import subprocess
import sys
import threading
import time
import webbrowser
from pathlib import Path

ROOT     = Path(__file__).resolve().parent
ENV_FILE = ROOT / ".env"

# ─────────────────────────────────────────────────────────────────────────────
# COLOUR HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def green(s):  return f"\033[92m{s}\033[0m"
def red(s):    return f"\033[91m{s}\033[0m"
def yellow(s): return f"\033[93m{s}\033[0m"
def cyan(s):   return f"\033[96m{s}\033[0m"
def bold(s):   return f"\033[1m{s}\033[0m"

# ─────────────────────────────────────────────────────────────────────────────
# LOAD EXISTING .env
# ─────────────────────────────────────────────────────────────────────────────

def load_env() -> dict:
    """Read current .env file into a dictionary."""
    data = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                data[k.strip()] = v.strip().strip('"').strip("'")
    return data


def save_env(data: dict):
    """Write the dictionary back to .env file."""
    lines = [
        "# OmniRecon AI — Environment Variables",
        "# Generated by start_backend.py",
        "# DO NOT commit this file to Git!\n",
    ]
    for k, v in data.items():
        lines.append(f'{k}="{v}"')
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

# ─────────────────────────────────────────────────────────────────────────────
# INSTALL PACKAGES
# ─────────────────────────────────────────────────────────────────────────────

def install_packages():
    req = ROOT / "backend" / "requirements.txt"
    print(f"\n{cyan('📦 Installing Python packages...')}")
    packages = [
        ("flask",          "Flask web framework"),
        ("flask-cors",     "Cross-origin support"),
        ("requests",       "HTTP client for APIs"),
        ("dnspython",      "Real DNS queries"),
        ("python-whois",   "Real WHOIS lookup"),
        ("ping3",          "Real ICMP ping"),
    ]
    for pkg, desc in packages:
        print(f"   Installing {pkg:<20} ({desc})...", end=" ", flush=True)
        r = subprocess.run(
            [sys.executable, "-m", "pip", "install", "-q", pkg],
            capture_output=True
        )
        print(green("✓") if r.returncode == 0 else yellow("⚠ failed"))

# ─────────────────────────────────────────────────────────────────────────────
# API KEY SETUP WIZARD
# ─────────────────────────────────────────────────────────────────────────────

API_KEYS = [
    {"key": "IPINFO_API_KEY",      "name": "IPInfo.io — IP Geolocation",          "url": "https://ipinfo.io/signup",                "cost": "FREE — 50,000 req/month",  "tools": "IP Geolocation, ASN Lookup"},
    {"key": "VIRUSTOTAL_API_KEY",  "name": "VirusTotal — Malware & Hash",          "url": "https://www.virustotal.com",              "cost": "FREE — 500 req/day",       "tools": "AI Malware Analyzer, Hash Lookup"},
    {"key": "ABUSEIPDB_API_KEY",   "name": "AbuseIPDB — IP Reputation",            "url": "https://www.abuseipdb.com",               "cost": "FREE — 1,000 req/day",     "tools": "IP Reputation tool"},
    {"key": "ALIENVAULT_API_KEY",  "name": "AlienVault OTX — Threat Intelligence", "url": "https://otx.alienvault.com",              "cost": "FREE — unlimited",         "tools": "IOC Lookup, Threat Intelligence"},
    {"key": "GREYNOISE_API_KEY",   "name": "GreyNoise — IP Scanner Detection",     "url": "https://greynoise.io",                    "cost": "FREE — community tier",    "tools": "IP context & scanner detection"},
    {"key": "SECURITYTRAILS_KEY",  "name": "SecurityTrails — Historical DNS",      "url": "https://securitytrails.com",              "cost": "FREE — 50 req/month",      "tools": "IP History, Reverse IP Lookup"},
    {"key": "SHODAN_API_KEY",      "name": "Shodan — Network Intelligence",        "url": "https://account.shodan.io",               "cost": "FREE — limited tier",      "tools": "Enhanced network scan data"},
    {"key": "HIBP_API_KEY",        "name": "HaveIBeenPwned — Email Breach",        "url": "https://haveibeenpwned.com/API/Key",       "cost": "PAID — $3.50/month",       "tools": "Email Account Exposure (password breach is FREE!)"},
]


def setup_api_keys(env: dict) -> dict:
    """Interactive wizard to configure API keys."""
    print(f"\n{bold('═' * 60)}")
    print(f"{bold('  🔑  API KEY SETUP WIZARD')}")
    print(f"{bold('═' * 60)}")
    print(f"""
  API keys make tools produce {green('REAL')} results instead of simulations.
  All keys below are {green('FREE')} to register.
  Press {cyan('Enter')} to skip any key (tool will use simulation).
  Press {cyan('Q')} at any prompt to finish and start the server.
    """)

    changed = False
    for item in API_KEYS:
        k        = item["key"]
        current  = env.get(k, "")
        is_set   = bool(current)

        status = green("✓ Already set") if is_set else red("✗ Not set (simulation)")
        cost   = green(item["cost"]) if "FREE" in item["cost"] else yellow(item["cost"])

        print(f"  {bold(item['name'])}")
        print(f"    Status   : {status}")
        print(f"    Cost     : {cost}")
        print(f"    Tools    : {cyan(item['tools'])}")
        print(f"    Register : {item['url']}")

        if is_set:
            prompt = f"    New key  : [keep current, press Enter to keep / type new key] → "
        else:
            prompt = f"    Your key : [press Enter to skip, type key to activate] → "

        try:
            val = input(prompt).strip()
        except (KeyboardInterrupt, EOFError):
            val = ""

        if val.lower() == "q":
            print(f"\n  {yellow('Skipping remaining keys and starting server...')}\n")
            break

        if val:
            env[k] = val
            changed = True
            print(f"    {green('✓ Key saved!')}")
        elif is_set:
            print(f"    {cyan('→ Keeping existing key.')}")
        else:
            print(f"    {yellow('→ Skipped — tool will use simulation.')}")

        print()

    if changed:
        save_env(env)
        print(f"  {green('✓ API keys saved to .env file.')}\n")

    return env


def admin_setup(env: dict) -> dict:
    """Optionally change admin credentials."""
    print(f"\n  {bold('🔐  Admin Account')}")
    current_email = env.get("ADMIN_EMAIL", "admin@omnirecon.ai")
    current_pass  = env.get("ADMIN_PASSWORD", "admin123")

    if current_pass == "admin123":
        print(f"  {red('⚠  WARNING: Default password is still set!')}")
        print(f"  Email   : {current_email}")
        print(f"  Password: {red('admin123  ← CHANGE THIS!')}")
        try:
            change = input("  Change admin password now? [y/N] → ").strip().lower()
        except (KeyboardInterrupt, EOFError):
            change = "n"

        if change == "y":
            try:
                new_email = input(f"  New email [{current_email}] → ").strip()
                new_pass  = input("  New password → ").strip()
            except (KeyboardInterrupt, EOFError):
                new_email = new_pass = ""

            if new_email:
                env["ADMIN_EMAIL"]    = new_email
            if new_pass and len(new_pass) >= 6:
                env["ADMIN_PASSWORD"] = new_pass
                print(f"  {green('✓ Admin credentials updated.')}")
            else:
                print(f"  {yellow('Password must be at least 6 chars — keeping default.')}")
            save_env(env)
    else:
        print(f"  {green('✓ Custom admin password is set.')}")

    print()
    return env

# ─────────────────────────────────────────────────────────────────────────────
# MAIN LAUNCHER
# ─────────────────────────────────────────────────────────────────────────────

def open_browser():
    time.sleep(2.5)
    webbrowser.open("http://127.0.0.1:5000")


def print_banner():
    print(f"""
{bold('╔══════════════════════════════════════════════════════════╗')}
{bold('║                                                          ║')}
{bold('║')}   {cyan('🛡️  OmniRecon AI — Smart Backend Launcher')}             {bold('║')}
{bold('║')}   {cyan('Unified Intelligence & Security Framework')}              {bold('║')}
{bold('║')}                                                          {bold('║')}
{bold('╚══════════════════════════════════════════════════════════╝')}
""")


def main():
    os.system("cls" if os.name == "nt" else "clear")
    print_banner()

    # Check Python version
    if sys.version_info < (3, 8):
        print(red("❌ Python 3.8+ required!"))
        sys.exit(1)
    print(f"  {green('✓')} Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")

    # Install packages
    install_packages()

    # Load existing .env
    env = load_env()

    # Ask whether to set up keys
    print(f"\n  {bold('Do you want to set up / update API keys?')}")
    print(f"  (Recommended for first-time setup or to add new keys)")
    try:
        ans = input("  Setup keys now? [Y/n] → ").strip().lower()
    except (KeyboardInterrupt, EOFError):
        ans = "n"

    if ans != "n":
        env = setup_api_keys(env)
        env = admin_setup(env)

    # Set environment variables from .env for this process
    for k, v in env.items():
        os.environ.setdefault(k, v)

    # Open browser
    threading.Thread(target=open_browser, daemon=True).start()

    # Start server
    os.chdir(str(ROOT))
    sys.path.insert(0, str(ROOT))

    print(f"\n{bold('═' * 60)}")
    print(f"  {green('🚀 Starting OmniRecon AI Backend...')}")
    print(f"     Website : {cyan('http://127.0.0.1:5000')}")
    print(f"     Health  : {cyan('http://127.0.0.1:5000/api/health')}")
    print(f"  {yellow('Press Ctrl+C to stop')}")
    print(f"{bold('═' * 60)}\n")

    try:
        from backend.server import main as server_main
        server_main()
    except KeyboardInterrupt:
        print(f"\n\n  {yellow('👋 Shutting down OmniRecon AI...')}")
    except Exception as e:
        print(f"\n{red(f'❌ Error: {e}')}")
        print("\nTry running directly:")
        print("  python backend/server.py")
        sys.exit(1)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n{yellow('👋 Goodbye!')}")
