import { useState } from "react";
import { Button, Input, ResultBox, Badge, Spinner } from "../lib/ui";
import { seeded, pick, randInt, delay } from "../lib/sim";
import { addHistory } from "../lib/history";

const VECTORS = ["Subdomain takeover via dangling CNAME", "Credential stuffing on exposed login portal", "SQL injection on legacy /search endpoint", "Phishing campaign using look-alike domain", "Exposed .git directory leaking source", "Outdated TLS (1.0/1.1) enabling MITM", "Open Redis instance without auth", "Reflected XSS in URL parameter", "Default credentials on admin panel", "Misconfigured S3 bucket public read", "SSRF", "Unpatched CVE in web framework"];
const RECS = ["Enable WAF and rate-limiting on auth endpoints", "Rotate exposed secrets & enforce MFA", "Patch framework to latest LTS version", "Configure HSTS and disable legacy TLS", "Implement CSP and input sanitization", "Deploy DMARC reject policy & monitor look-alikes"];

export function RiskAnalyzer() {
  const [target, setTarget] = useState(""); const [res, setRes] = useState<any>(null); const [loading, setLoading] = useState(false);
  const go = async () => { setLoading(true); await delay(1100); const rng = seeded(target + "risk"); const score = randInt(rng, 15, 95); const level = score >= 80 ? "Critical" : score >= 60 ? "High" : score >= 40 ? "Medium" : "Low"; const vectors = [...VECTORS].sort(() => rng() - 0.5).slice(0, randInt(rng, 3, 5)).map(v => ({ v, sev: pick(rng, ["High", "Medium", "Critical", "Low"]) })); const recs = [...RECS].sort(() => rng() - 0.5).slice(0, 4); const factors = [{ k: "Attack Surface", v: randInt(rng, 20, 100) }, { k: "Exposure", v: randInt(rng, 20, 100) }, { k: "Patch Hygiene", v: randInt(rng, 20, 100) }, { k: "Threat Activity", v: randInt(rng, 20, 100) }]; setRes({ score, level, vectors, recs, factors }); setLoading(false); addHistory({ module: "AI Analysis Center", tool: "AI Risk Analyzer", target, summary: `Risk ${score}/100 · ${vectors.length} vectors`, risk: level as any }); };
  const color = (l: string) => l === "Critical" || l === "High" ? "#f43f5e" : l === "Medium" ? "#f59e0b" : "#10b981";
  const sevColor = (s: string) => s === "Critical" || s === "High" ? "rose" : s === "Medium" ? "amber" : "emerald";
  return <div><p className="mb-3 text-sm text-slate-400">AI engine rates risk, predicts attack vectors and recommends remediation.</p><div className="flex gap-2"><Input value={target} onChange={e => setTarget(e.target.value)} placeholder="domain, IP or asset" /><Button onClick={go}>⚡ Analyze</Button></div>{loading && <div className="mt-4"><Spinner /></div>}{res && !loading && <div className="mt-4 space-y-4 fade-in"><ResultBox><div className="flex items-center gap-5"><div className="relative h-28 w-28"><svg viewBox="0 0 100 100" className="h-28 w-28 -rotate-90"><circle cx="50" cy="50" r="42" fill="none" stroke="#1e293b" strokeWidth="10" /><circle cx="50" cy="50" r="42" fill="none" stroke={color(res.level)} strokeWidth="10" strokeLinecap="round" strokeDasharray={`${(res.score / 100) * 264} 264`} /></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-3xl font-bold" style={{ color: color(res.level) }}>{res.score}</span><span className="text-[10px] text-slate-500">/100</span></div></div><div><div className="text-xs uppercase tracking-wider text-slate-500">Risk Level</div><div className="text-2xl font-bold" style={{ color: color(res.level) }}>{res.level}</div></div></div></ResultBox><ResultBox title="Risk Factors">{res.factors.map((f: any) => <div key={f.k} className="mb-2"><div className="flex justify-between text-xs"><span className="text-slate-400">{f.k}</span><span className="mono text-slate-200">{f.v}%</span></div><div className="mt-1 h-1.5 w-full rounded-full bg-slate-800"><div className="h-full rounded-full bg-teal-500" style={{ width: `${f.v}%` }} /></div></div>)}</ResultBox><ResultBox title="Predicted Attack Vectors"><div className="space-y-2">{res.vectors.map((v: any, i: number) => <div key={i} className="flex items-center justify-between gap-2 rounded-md border border-slate-800 px-3 py-2 text-sm"><span className="text-slate-200">{v.v}</span><Badge color={sevColor(v.sev) as any}>{v.sev}</Badge></div>)}</div></ResultBox><ResultBox title="AI Recommendations"><ul className="space-y-1.5 text-sm text-slate-300">{res.recs.map((r: string, i: number) => <li key={i}>✓ {r}</li>)}</ul></ResultBox></div>}</div>;
}

export function VulnScanner() {
  const [target, setTarget] = useState(""); const [res, setRes] = useState<any>(null); const [loading, setLoading] = useState(false);
  const CVES = ["CVE-2024-3094", "CVE-2023-44487", "CVE-2021-44228", "CVE-2024-21413", "CVE-2023-23397", "CVE-2022-22965"];
  const go = async () => { setLoading(true); await delay(1300); const rng = seeded(target + "vuln"); const n = randInt(rng, 3, 7); const findings = Array.from({ length: n }, () => ({ cve: pick(rng, CVES), title: pick(rng, ["Remote Code Execution", "Authentication Bypass", "Information Disclosure", "Denial of Service", "Privilege Escalation", "Cross-Site Scripting"]), cvss: (rng() * 6 + 4).toFixed(1), conf: randInt(rng, 60, 99) })).sort((a, b) => +b.cvss - +a.cvss); setRes(findings); setLoading(false); const max = +findings[0].cvss; addHistory({ module: "AI Analysis Center", tool: "AI Vulnerability Scanner", target, summary: `${n} vulns, max CVSS ${findings[0].cvss}`, risk: max >= 9 ? "Critical" : max >= 7 ? "High" : "Medium" }); };
  const sev = (c: number) => c >= 9 ? "rose" : c >= 7 ? "amber" : "emerald";
  return <div><div className="flex gap-2"><Input value={target} onChange={e => setTarget(e.target.value)} placeholder="target URL / host" /><Button onClick={go}>Scan</Button></div>{loading && <div className="mt-4"><Spinner /></div>}{res && !loading && <ResultBox title={`${res.length} Vulnerabilities`}><div className="space-y-2">{res.map((f: any, i: number) => <div key={i} className="rounded-md border border-slate-800 p-3"><div className="flex items-center justify-between"><span className="font-medium text-slate-100">{f.title}</span><Badge color={sev(+f.cvss) as any}>CVSS {f.cvss}</Badge></div><div className="mt-1 flex justify-between text-xs text-slate-500"><span className="mono">{f.cve}</span><span>AI confidence {f.conf}%</span></div></div>)}</div></ResultBox>}</div>;
}

export function MalwareAnalyzer() {
  const [name, setName] = useState(""); const [hash, setHash] = useState(""); const [res, setRes] = useState<any>(null); const [loading, setLoading] = useState(false);
  const onFile = (f?: File) => { if (f) { setName(f.name); setHash((f.size + f.name).split("").reduce((a, c) => a + c.charCodeAt(0), 0).toString(16).padStart(8, "0").repeat(8).slice(0, 64)); } };
  const go = async () => { setLoading(true); await delay(1200); const rng = seeded((name || hash) + "mw"); const malicious = rng() > 0.45; const detections = randInt(rng, malicious ? 18 : 0, malicious ? 64 : 3); setRes({ verdict: malicious ? "Malicious" : detections > 0 ? "Suspicious" : "Clean", detections, engines: 70, family: malicious ? pick(rng, ["Trojan.GenericKD", "Win32.Emotet", "Android.Cerberus", "Ransom.LockBit"]) : "—", behaviors: malicious ? [...["Drops executable to %TEMP%", "Modifies registry Run keys", "Contacts C2 server", "Encrypts user files", "Disables Windows Defender"]].sort(() => rng() - 0.5).slice(0, 4) : [] }); setLoading(false); addHistory({ module: "AI Analysis Center", tool: "AI Malware Analyzer", target: name || hash.slice(0, 16), summary: `Verdict: ${malicious ? "Malicious" : "Clean"}`, risk: malicious ? "Critical" : detections > 0 ? "Medium" : "Low" }); };
  return <div><label className="block cursor-pointer rounded-lg border border-dashed border-slate-700 p-6 text-center text-sm text-slate-400 hover:border-teal-500"><input type="file" className="hidden" onChange={e => onFile(e.target.files?.[0])} />📁 Drop a file or click to select</label><div className="mt-3 flex gap-2"><Input value={hash} onChange={e => setHash(e.target.value)} placeholder="or paste a SHA-256 hash" className="mono" /><Button onClick={go}>Analyze</Button></div>{loading && <div className="mt-4"><Spinner /></div>}{res && !loading && <ResultBox title={name || "File Analysis"}><div className="mb-3 flex items-center justify-between"><span className="text-lg font-bold" style={{ color: res.verdict === "Malicious" ? "#f43f5e" : res.verdict === "Suspicious" ? "#f59e0b" : "#10b981" }}>{res.verdict}</span><Badge color={res.verdict === "Clean" ? "emerald" : "rose"}>{res.detections}/{res.engines} engines</Badge></div>{res.behaviors.length > 0 && <ul className="space-y-1 text-sm text-slate-300">{res.behaviors.map((b: string, i: number) => <li key={i}>⚠ {b}</li>)}</ul>}</ResultBox>}</div>;
}

const PERMS = ["READ_SMS", "SEND_SMS", "READ_CONTACTS", "ACCESS_FINE_LOCATION", "CAMERA", "RECORD_AUDIO", "READ_CALL_LOG", "SYSTEM_ALERT_WINDOW", "REQUEST_INSTALL_PACKAGES", "BIND_ACCESSIBILITY_SERVICE", "INTERNET", "WRITE_EXTERNAL_STORAGE"];
export function ApkAnalyzer() {
  const [name, setName] = useState(""); const [res, setRes] = useState<any>(null); const [loading, setLoading] = useState(false);
  const go = async () => { setLoading(true); await delay(1200); const rng = seeded(name + "apk"); const perms = PERMS.filter(() => rng() > 0.45); const dangerous = perms.filter(p => ["READ_SMS", "SEND_SMS", "BIND_ACCESSIBILITY_SERVICE", "REQUEST_INSTALL_PACKAGES", "READ_CALL_LOG", "SYSTEM_ALERT_WINDOW"].includes(p)); const score = Math.min(100, dangerous.length * 18 + randInt(rng, 0, 20)); setRes({ pkg: `com.${pick(rng, ["app", "mobile", "secure", "free"])}.${name.replace(/\W/g, "").toLowerCase() || "demo"}`, version: `${randInt(rng, 1, 9)}.${randInt(rng, 0, 9)}.${randInt(rng, 0, 9)}`, minSdk: randInt(rng, 19, 33), targetSdk: randInt(rng, 30, 34), perms, dangerous, score, trackers: randInt(rng, 0, 8), certificates: pick(rng, ["Valid (Google Play)", "Self-signed ⚠", "Debug certificate ⚠"]) }); setLoading(false); addHistory({ module: "AI Analysis Center", tool: "APK Analyzer", target: name, summary: `${perms.length} perms, ${dangerous.length} dangerous`, risk: score >= 70 ? "High" : score >= 40 ? "Medium" : "Low" }); };
  return <div><label className="block cursor-pointer rounded-lg border border-dashed border-slate-700 p-6 text-center text-sm text-slate-400 hover:border-teal-500"><input type="file" accept=".apk" className="hidden" onChange={e => setName(e.target.files?.[0]?.name || "")} />📱 Select an .apk file to analyze</label>{name && <div className="mt-2 text-sm text-slate-300 mono">{name}</div>}<Button className="mt-3" onClick={go} disabled={!name}>Analyze APK</Button>{loading && <div className="mt-4"><Spinner /></div>}{res && !loading && <ResultBox title="APK Static Analysis"><div className="mb-3 grid grid-cols-2 gap-2 text-sm"><div className="rounded border border-slate-800 p-2"><div className="text-xs text-slate-500">Package</div><span className="mono text-slate-200">{res.pkg}</span></div><div className="rounded border border-slate-800 p-2"><div className="text-xs text-slate-500">Version</div><span className="mono">{res.version}</span></div><div className="rounded border border-slate-800 p-2"><div className="text-xs text-slate-500">SDK</div><span className="mono">min {res.minSdk}</span></div><div className="rounded border border-slate-800 p-2"><div className="text-xs text-slate-500">Risk Score</div><Badge color={res.score >= 70 ? "rose" : res.score >= 40 ? "amber" : "emerald"}>{res.score}/100</Badge></div></div><div className="flex flex-wrap gap-2">{res.perms.map((p: string) => <Badge key={p} color={res.dangerous.includes(p) ? "rose" : "slate"}>{p}</Badge>)}</div></ResultBox>}</div>;
}
